# Generated by Django 4.1.7 on 2023-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=255)),
                ("Text", models.CharField(max_length=255)),
                ("Text_order", models.IntegerField()),
                ("Check", models.BooleanField()),
            ],
        ),
    ]
